[package]
name = "e_window"
description = "A window tool. Think WinAPI ShowMessageBox; but more than that."
license = "MIT"
version = "0.1.0"
authors = ["David Horner"]
edition = "2021"
publish = true


[dependencies]
chrono = "0.4.41"
eframe = {version="0.31.1",features=["persistence","serde"]}
egui = { version= "0.31.1",features=["persistence","serde","log"]}
getargs = "0.5.0"
serde = { version = "1.0.219", features = ["derive"] }
shell-words = "1.1.0"
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }
