name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose -- --skip test_bacon_help --skip test_bacon_version  --skip testgen_ex_builtin --skip test_sample_count_in_testgen_ex_project --skip test_single_example_functionality

